name: Build & Push Docker Image to Docker Hub

on:
  pull_request:
      types: [closed]

env:
  DOCKER_IMAGE_NAME: python-uv

permissions:
  contents: write

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install commitizen
        run: |
          python -m pip install --upgrade pip
          pip install -U commitizen

      - name: Dry run to get new tag
        id: get_tag
        shell: bash
        run: |
          # tag=$(cz bump --yes --no-verify --changelog --dry-run)
          TAG=$(echo "$(cz bump --yes --no-verify --changelog --dry-run)" | sed -n 's/^tag to create: v//p')
          echo "Tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cz bump --yes
          git push origin HEAD:master
          git push origin --tags

  build-and-push:
    runs-on: ubuntu-latest
    needs: bump-version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show version
        run: |
          echo "TAG: ${{ needs.bump-version.outputs.tag }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push v3.12
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.3_12
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}_3.12:${{ needs.bump-version.outputs.tag }}

      - name: Build and push v3.13
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.3_13
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}_3.13:${{ needs.bump-version.outputs.tag }}

      - name: Build and push v3.14
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.3_14
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}_3.14:${{ needs.bump-version.outputs.tag }}

  create-github-release:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Show version
        run: |
          echo "TAG: ${{ needs.bump-version.outputs.tag }}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ needs.bump-version.outputs.tag }}
          release_name: v${{ needs.bump-version.outputs.tag }}
          body: "Automated release generated by GitHub Actions."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
