name: Build & Push Docker Image to Docker Hub

on:
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get PR merge commit
        id: merge_commit
        run: |
          MERGE_COMMIT=${{ github.event.pull_request.merge_commit_sha }}
          echo "MERGE_COMMIT=$MERGE_COMMIT"
          echo "MERGE_COMMIT=$MERGE_COMMIT" >> $GITHUB_ENV

      - name: Get last tag for merge commit
        id: get_tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags $MERGE_COMMIT)
          echo "TAG=$TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python-uv:$TAG .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/python-uv:$TAG
